version: "3.8"

services:
  app:
    image: bitnami/php-fpm:7.4.28
    container_name: app
    command: php artisan serve --port=80
    working_dir: /app
    depends_on:
      - mariadb-server
      - rabbitmq
    environment:
      - DB_HOST=mariadb-server
      - REDIS_PASSWORD=secret
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    volumes:
      - ./:/app
    ports:
      - "80:80"
    networks:
      - app

  mariadb-server:
    image: bitnami/mariadb:10.5
    container_name: mariadb-server
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=secret
      - MARIADB_DATABASE=laravel
    volumes:
      - db-data:/bitnami/mariadb/data
    ports:
      - "3308:3306"
    networks:
      - app

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app

  phpmyadmin:
    image: bitnami/phpmyadmin:5.1.3
    container_name: phpmyadmin
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mariadb-server
    networks:
      - app

volumes:
  db-data:


networks:
  app:
    name: app_network
